server:
  port: 81

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zbl_missyou_v2?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true



zbl:
  security:
    jwt_key: 12345678
    token_expired_time: 86400000

  sku:
    limit_buy_count: 99