server:
  port: 81

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zbl_missyou_v2?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

redis:
  ip: localhost
  port: 6379
  expired_pattern: __keyevent@{0}__:expired
  db:
    # 订单过期数据库index
    order_expired: 7

rocketmq:
  namesrv_addr: localhost:9876
  producer:
    group: zbl-producer
  consumer:
    group: zbl-consumer
  # 1s 5s 10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 20m 30m 1h 2h 选下标位置（1：1s，2：5s，3：10s）
  delay_level: 2
  topic:
    order: order


zbl:
  security:
    # 令牌钥匙
    jwt_key: 12345678
    # 令牌过期时间
    token_expired_time: 86400000
  sku:
    # 最大购买数量
    limit_buy_count: 99
  order:
    # 订单待支付到期时间
    limit_pay_time: 3600
    # 接收微信支付通知回调域名
    wx_notify_host: localhost:81
    # 接收微信支付通知回调域名api
    wx_notify_path: v1/pay/wechat/pay_notify
  money:
    # 金额运算模式（0：向上取整，1：向下取整，2：正上负上，3：正下负下，4：四舍五入，5：五舍六入，6：银行家，7：抛弃模式）
    mode: 6