server:
  port: 81

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zbl_missyou?characterEncoding=utf-8&serverTimezone=GMT%2B8£
    username: root£
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true