spring:
  profiles:
    active: dev
  jackson:
    # 字段改成下划线形式
    # property-naming-strategy: SNAKE_CASE
    serialization:
      # 序列化时间时返回时间戳
      WRITE_DATES_AS_TIMESTAMPS: true

missyou:
  api-path: com.blcheung.missyou.api

wx:
  app_id: 你的appId
  secret: 你的secret
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code